name: super-teams
version: '${version}'
main: org.minty.superteams.Super_teams
api-version: '1.18'
#depend:
#  - [NBTAPI]
commands:
  switch:
    description: Меняет команду игрока
  set_teleport_pos:
    description: Установить точку для телепортации
  teleport_to_team_point:
    description: Телепортироваться к точке команды
  getList:
    description: Вывести список игроков команды